/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FilesRouteImport } from './routes/files'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesListRouteImport } from './routes/files.list'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesListRoute = FilesListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => FilesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files': typeof FilesRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/files/list': typeof FilesListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof FilesRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/files/list': typeof FilesListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/files': typeof FilesRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/files/list': typeof FilesListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files'
    | '/login'
    | '/admin/audit'
    | '/admin/permissions'
    | '/admin/users'
    | '/files/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files'
    | '/login'
    | '/admin/audit'
    | '/admin/permissions'
    | '/admin/users'
    | '/files/list'
  id:
    | '__root__'
    | '/'
    | '/files'
    | '/login'
    | '/admin/audit'
    | '/admin/permissions'
    | '/admin/users'
    | '/files/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesRoute: typeof FilesRouteWithChildren
  LoginRoute: typeof LoginRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/list': {
      id: '/files/list'
      path: '/list'
      fullPath: '/files/list'
      preLoaderRoute: typeof FilesListRouteImport
      parentRoute: typeof FilesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FilesRouteChildren {
  FilesListRoute: typeof FilesListRoute
}

const FilesRouteChildren: FilesRouteChildren = {
  FilesListRoute: FilesListRoute,
}

const FilesRouteWithChildren = FilesRoute._addFileChildren(FilesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesRoute: FilesRouteWithChildren,
  LoginRoute: LoginRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
